"""Add detected_objects field to Photo model

Revision ID: e4820bdd008e
Revises: 4450cf27289f
Create Date: 2025-03-14 19:11:14.606787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4820bdd008e'
down_revision = '4450cf27289f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detected_objects', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_column('detected_objects')

    # ### end Alembic commands ###
